### ISSUE TITLE
JSON Data of all the links

### ISSUE THREAD

**Issue by ankithaldar1995** [kweiberth/songlink#1]
Can I get the JSON data of all the links ?

**Comment by kweiberth** [comment]
Not at the moment. I have considered opening up an API of all of our data, but I'm not quite ready to do this. Would you be able to incorporate Songlink URLs instead?

**Comment by matteolobello** [comment]
Still nothing?

**Comment by kweiberth** [comment]
For anyone following this: still no timeline on a public API. There are some legitimate technical and legal (e.g. terms of service from our API partners) obstacles that we have to figure out first. Long term, we want to have a full-fledged API (we are a small team, want to stay that way, and want to enable developers to build cool apps that we never could), but no promises and no timeline. It is not our top priority at the moment.

We do offer redirect URLs which could possibly end up being the only way we offer an "API". Even in their current form, redirect URLs are at least 99% of a full API for our match data. At the end of the day, they will handle all types of complexity (e.g. country availability) that would have to be implemented by the client if we had a full-fledged API. The handling of rare edge cases will be improved, too. 

More info about redirect URLs can be found here: https://github.com/kweiberth/songlink#redirect-urls. 

Lastly, we also offer an embeddable experience: http://help.song.link/embed/embed-songlinks-into-your-website-or-blog.

Please reach out to hello@song.link if you have any questions or would like to chat about collaborating with us in some way.

**Comment by kweiberth** [comment]
Wow, this is an old issue, apologies for leaving it dangling! We do now have a public API, the docs for which can be found here: https://www.notion.so/odesli/Public-API-d8093b1bb8874f8b85527d985c4f9e68

The API is still in "alpha", but it's been active for a while and we have many developers using it. I'm planning a "v1" stable release, probably within the next few months.
