### ISSUE TITLE
Add preference to auto open music app of choice

### ISSUE THREAD

**Issue by cheeragpatel** [kweiberth/songlink#2]
The old version had this feature, could this be added to the current version?

**Comment by kweiberth** [comment]
Possibly. We had received a fair amount of complaints about it so I decided not to keep it on the new platform. 

I think one of the issues with it was that the preferences weren't being store in webviews of external apps (Facebook, Twitter, etc), and so at the best it wasn't working all the time and at the worst it was annoying that we kept asking for the user's preference. 

We could probably add it back in a less obtrusive way. Thanks for the feedback.

**Comment by kweiberth** [comment]
Closing this since there hasn't been a continuation of the conversation. We will not be adding this right now, but it is something we will continue to evaluate.
