### ISSUE TITLE
Blank page on Android

### ISSUE THREAD

**Issue by verekia** [kweiberth/songlink#3]
Hey there! Thank you for making song.link :)

When I try to access any song.link URL from Android (with a Nexus 5X), I get a white page.

Browser info: https://www.whatismybrowser.com/w/J3RQWKB

I noticed some behavior that might be useful for debugging:
It seems like the issue happens early in the request, because when I try to access https://song.link/i/1276710794 from the desktop, the "/us/" is inserted automatically. On Android though, https://song.link/i/1276710794 shows a blank page without even trying to add the "/us/" part. Either way, getting a blank page with or without the "/us/" bit.

**Comment by kweiberth** [comment]
@verekia thanks for reaching out with this info, and for taking the effort to debug it a bit. Many, many thanks. I will look into this soon and get back to you when I find out what's going on here.

**Comment by verekia** [comment]
No problem!

Also, when I "Request desktop site" on Chrome for Android, it works normally.

**Comment by kweiberth** [comment]
Thanks for bringing this to our attention and providing valuable info. This bug has been fixed. Apologies for the delay. I fixed it late last night and forgot to get back to you. It also should've been fixed sooner 😞. That's my bad. 

Anyway, it should be fixed now. Please do reach out if you're still having issues.

**Comment by verekia** [comment]
Works as expected now, thank you for the quick fix!
