### ISSUE TITLE
Feature request: Link to an album

### ISSUE THREAD

**Issue by ezzatron** [kweiberth/songlink#4]
Songlink is cool, but my friends and I don't share songs, we share albums. The ability to link to an album would surely net you more users ;)

**Comment by kweiberth** [comment]
Hey @ezzatron, thanks for reaching out! We do support albums, just not in our search bar yet. Easiest thing to do is to add the album link after our domain, like so: 

https://song.link/https://open.spotify.com/album/5bCk3kWAy2JbbTfHqzZCII

**Comment by ezzatron** [comment]
Awesome! I'll have to try it out. Any idea if it will work with the Slack integration?

**Comment by kweiberth** [comment]
Yes, our Slack integration will work with album URLs. The search functionality will return only songs, however, but if you copy paste an album link, it will work.

**Comment by ezzatron** [comment]
Just tried it out, worked great! I'm gonna sling you some 💰 because that shit was cash ;)

**Comment by kweiberth** [comment]
Glad it worked. Thanks for the feedback and for using our product. Feel free to reach out at any time with questions, feedback, ideas, etc

**Comment by kweiberth** [comment]
You weren't lying about slinging some dough ;) 🤑 . Much appreciated 🙏. It will help us out with our running costs.

**Comment by ezzatron** [comment]
No worries, thanks for making something cool!
