### ISSUE TITLE
Ability to link full playlists?

### ISSUE THREAD

**Issue by snowgears** [kweiberth/songlink#5]
The ability to link full playlists would be very cool. You could simply use the system you currently have in place for each song and then iterate through each song in the playlist generating a link.

Just a thought. Another cool feature could be fully importing/exporting playlists from songlink so that a user could link a playlist from spotify and import from that link into another platform like tidal or apple music.

I realize that would be a bit more work but would definitely be a cool feature.

**Comment by kweiberth** [comment]
Hey @snowgears thanks for the feedback. I agree, playlist support would be a killer feature. There are some technical challenges, but the first option you describe seems pretty doable. After all, is a playlist not just a collection of song(links)??

I'm working on opening up our API as well, so it might be something developers like yourself could build.

**Comment by snowgears** [comment]
Thanks for responding! It sounds like even better things are on their way. Let me know if you need anything and I'll gladly do what I can to help.

I will be looking out for the public API. Thanks!
